### ISSUE TITLE
Dupe with Jobs

### ISSUE THREAD

**Issue by Faceless0102** [OmerBenGera/WildTools#2]
Hey!

So I noticed that points from jobs are getting duplicated if I mine ores with trench pickaxes.
WildTools version 2.10.4
Jobs version 4.16.3

**Comment by Faceless0102** [comment]
and I think the money and exp is also duped

**Comment by OmerBenGera** [comment]
You can remove the jobs plugin from the supported plugins.

**Comment by Faceless0102** [comment]
You mean from
  other-plugins:
  - Jobs
 ?

**Comment by OmerBenGera** [comment]
yes

**Comment by Faceless0102** [comment]
Seems like it's working thanks!

**Comment by Faceless0102** [comment]
I still have the issue. I'm gonna show a video to you

**Comment by Faceless0102** [comment]
https://imgur.com/a/5C2vytR

**Comment by Faceless0102** [comment]
The values are 12x bigger than should be

**Comment by OmerBenGera** [comment]
If you remove Jobs from the plugins list, it will not be detected by Jobs.

**Comment by Faceless0102** [comment]
It is removed.

**Comment by Faceless0102** [comment]
```
events-manipulations:
  # A list of all the plugins that handle claims here on your server.
  # If one of the plugins here cancel the events, then WT will know that the player doesn't have access.
  claiming-plugins:
  - SuperiorSkyblock2
  # A list of all the other plugins that needs to know about breaking of blocks.
  # You can add your custom shops plugins, spawners plugin and more.
  # WildTools will not care if events are cancelled from this list. Therefore, if WildTools needs to know
  # if the events are cancelled from a plugin, add it to the 'claiming-plugins' section.
  other-plugins:
  - MineResetLite
```
